version: '3'

services:
    database:
        image: mariadb
        volumes:
            - 'database:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_DATABASE: formation
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - 3306:3306
    app:
        build:
            context: ./app
            args:
              phpversion: 7.4
        ports:
            - 8080:80
        volumes:
            - ../:/var/www/html:cached

volumes:
  database: {}
