kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: my-app
  name: deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-manager-binding
  namespace: my-app
subjects:
- kind: User
  name: deployer
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
