name: Test commit

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build application
      run: docker build --build-arg phpversion=7.4 -f docker/prod/Dockerfile . --tag agence301/base:latest

    - name: Docker login
      run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push docker
      run: docker push agence301/base:latest

    - name: Export kube config secret
      run: echo ${{ secrets.KUBECONFIG_SECRET }} | base64 --decode > ~/.kube/config

    - name: Kubectl rollout restart
      run: kubectl rollout restart -n my-app deployment my-app
